services:
    php:
        image: converter_webp
        container_name: converter_webp
        restart: always
        labels:
            - traefik.enable=true
            - traefik.http.routers.webpconverter.rule=Host(`webp-converter.ju2breizh.fr`)
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - webgateway
networks:
    webgateway:
        external: true
