services:
    php:
        image: converter_webp
        container_name: converter_webp
        restart: always
        labels:
            - "traefik.enable=true" # Active Traefik pour ce conteneur
            - "traefik.http.routers.webpconverter.rule=Host(`webp-converter.ju2breizh.fr`)" # Nom de domaine pour accéder au conteneur
            - "traefik.http.services.webpconverter.loadbalancer.server.port=80"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8089:80"
        volumes:
            - .:/var/www/html
        networks:
            - webgateway
networks:
    webgateway:
        external: true
